"""add fsrs scheduling fields to progress

Revision ID: 2e1ac0057547
Revises: 98325f06de1f
Create Date: 2026-06-11 22:22:25.800294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e1ac0057547'
down_revision: Union[str, None] = '98325f06de1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('due', sa.DateTime(timezone=True), nullable=True))
    op.add_column('progress', sa.Column('fsrs_card', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_progress_due'), 'progress', ['due'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_due'), table_name='progress')
    op.drop_column('progress', 'fsrs_card')
    op.drop_column('progress', 'due')
    # ### end Alembic commands ###
