"""add decks.owner_id

Revision ID: 3138c03fe912
Revises: ad2959f1ab76
Create Date: 2026-06-12 09:29:25.801405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3138c03fe912'
down_revision: Union[str, None] = 'ad2959f1ab76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_decks_owner_id'), 'decks', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'decks', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_index(op.f('ix_decks_owner_id'), table_name='decks')
    op.drop_column('decks', 'owner_id')
    # ### end Alembic commands ###
