"""add progress.flagged

Revision ID: 6ba98b688a2b
Revises: c4a25d937059
Create Date: 2026-06-12 07:49:21.730756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba98b688a2b'
down_revision: Union[str, None] = 'c4a25d937059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('flagged', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress', 'flagged')
    # ### end Alembic commands ###
