"""dedupe + unique private deck per owner

Revision ID: 91a92e1e1e35
Revises: f0cec26ddf58
Create Date: 2026-06-12 11:07:15.300279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a92e1e1e35'
down_revision: Union[str, None] = 'f0cec26ddf58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Merge any duplicate private decks per owner before enforcing uniqueness:
    # move cards from the extra decks onto the earliest kept deck, then delete extras.
    op.execute("""
        WITH ranked AS (
            SELECT id, owner_id,
                   row_number() OVER (PARTITION BY owner_id ORDER BY created_at, id) AS rn
            FROM decks WHERE owner_id IS NOT NULL
        ),
        keep AS (SELECT owner_id, id AS keep_id FROM ranked WHERE rn = 1),
        dupes AS (
            SELECT r.id AS dupe_id, k.keep_id
            FROM ranked r JOIN keep k ON r.owner_id = k.owner_id
            WHERE r.rn > 1
        )
        UPDATE cards SET deck_id = d.keep_id
        FROM dupes d WHERE cards.deck_id = d.dupe_id;
    """)
    op.execute("""
        WITH ranked AS (
            SELECT id,
                   row_number() OVER (PARTITION BY owner_id ORDER BY created_at, id) AS rn
            FROM decks WHERE owner_id IS NOT NULL
        )
        DELETE FROM decks WHERE id IN (SELECT id FROM ranked WHERE rn > 1);
    """)
    op.create_index('uq_decks_owner', 'decks', ['owner_id'], unique=True, postgresql_where=sa.text('owner_id IS NOT NULL'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_decks_owner', table_name='decks', postgresql_where=sa.text('owner_id IS NOT NULL'))
    # ### end Alembic commands ###
