"""add cards.owner_id

Revision ID: ad2959f1ab76
Revises: 6ba98b688a2b
Create Date: 2026-06-12 08:02:58.182442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2959f1ab76'
down_revision: Union[str, None] = '6ba98b688a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_cards_owner_id'), 'cards', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'cards', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_index(op.f('ix_cards_owner_id'), table_name='cards')
    op.drop_column('cards', 'owner_id')
    # ### end Alembic commands ###
