"""add decks table and cards.deck_id

Revision ID: be9920efebf7
Revises: 2e1ac0057547
Create Date: 2026-06-11 22:32:35.179199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9920efebf7'
down_revision: Union[str, None] = '2e1ac0057547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cards', sa.Column('deck_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_cards_deck_id'), 'cards', ['deck_id'], unique=False)
    op.create_foreign_key(None, 'cards', 'decks', ['deck_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_index(op.f('ix_cards_deck_id'), table_name='cards')
    op.drop_column('cards', 'deck_id')
    op.drop_table('decks')
    # ### end Alembic commands ###
