"""add decks.featured

Revision ID: c4a25d937059
Revises: be9920efebf7
Create Date: 2026-06-12 07:19:34.121661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a25d937059'
down_revision: Union[str, None] = 'be9920efebf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('featured', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'featured')
    # ### end Alembic commands ###
