"""add users.study_deck_ids

Revision ID: f0cec26ddf58
Revises: 3138c03fe912
Create Date: 2026-06-12 09:48:45.221227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0cec26ddf58'
down_revision: Union[str, None] = '3138c03fe912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('study_deck_ids', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'study_deck_ids')
    # ### end Alembic commands ###
